# Combining the NHANES Datas 2007-18

In [1]:
# The required libraries are imported.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
d1=pd.read_csv("newdata1.csv")
d2=pd.read_csv("newdata2.csv")
d3=pd.read_csv("newdata3.csv")
d4=pd.read_csv("newdata4.csv")
d5=pd.read_csv("newdata5.csv")
d6=pd.read_csv("newdata6.csv")
# Now the files containing the dietary dataset for year 2007-2018 are imported.
# These can be downloaded from NHANES.

In [3]:
d = pd.concat([d1, d2,d3,d4,d5,d6], ignore_index = True)
d.to_csv('filedata.csv')
d

In [4]:
d.describe()
# So the brief of the data is as follows.

,SEQN,WTDRD1,WTDR2D,DR1ILINE,DR1DRSTZ,DR1EXMER,DRABF,DRDINT,DR1DBIH,DR1DAY,...,DR1IM181,DR1IM201,DR1IM221,DR1IP182,DR1IP183,DR1IP184,DR1IP204,DR1IP205,DR1IP225,DR1IP226
count,7.890000e+05,7.890000e+05,789000.000000,7.890000e+05,7.890000e+05,7.890000e+05,7.890000e+05,7.890000e+05,789000.000000,789000.000000,...,789000.000000,789000.000000,789000.000000,789000.000000,789000.000000,789000.000000,789000.000000,789000.000000,789000.000000,789000.000000
mean,7.103097e+04,3.706569e+04,37299.504372,9.201654e+00,1.039659e+00,4.296310e+01,1.986465e+00,1.868048e+00,14.153873,4.513091,...,1.605756,0.017269,0.001688,0.976565,0.098739,0.000735,0.009124,0.001767,0.001304,0.003759
std,1.805917e+04,4.317877e+04,53614.200286,6.159536e+00,3.444070e-01,2.196296e+01,1.157358e-01,3.385023e-01,12.000354,2.186808,...,3.303622,0.059703,0.023637,2.277360,0.260448,0.008413,0.032205,0.022731,0.008669,0.038670
min,3.687825e-40,3.687825e-40,0.000000,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,-60.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5.517400e+04,1.155736e+04,7559.511807,4.000000e+00,1.000000e+00,2.300000e+01,2.000000e+00,2.000000e+00,5.000000,3.000000,...,0.000000,0.000000,0.000000,0.003000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,6.967400e+04,2.210739e+04,19203.001909,8.000000e+00,1.000000e+00,4.200000e+01,2.000000e+00,2.000000e+00,13.000000,5.000000,...,0.239000,0.000000,0.000000,0.110000,0.016000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,8.678000e+04,4.578552e+04,45214.577958,1.300000e+01,1.000000e+00,5.900000e+01,2.000000e+00,2.000000e+00,21.000000,6.000000,...,1.828000,0.012000,0.000000,0.902000,0.088000,0.000000,0.001000,0.000000,0.000000,0.000000
max,1.029560e+05,6.911395e+05,901995.118861,6.100000e+01,4.000000e+00,9.100000e+01,2.000000e+00,2.000000e+00,76.000000,7.000000,...,190.556000,5.489000,7.232000,154.515000,16.344000,0.631000,1.550000,2.155000,1.176000,4.356000

In [5]:
# Later we have imported Physical Measures(below BMI file) and  demographic dataset from NHANES dataset 2007-18.
# These files do contain calculated BMI,the age-sex,and other important parameters respectively.

df1=pd.read_csv("file_BMI2007.csv")
df2=pd.read_csv("file_BMI2009.csv")
df3=pd.read_csv("file_BMI2011.csv")
df4=pd.read_csv("file_BMI2013.csv")
df5=pd.read_csv("file_BMI2015.csv")
df6=pd.read_csv("file_BMI2017.csv")
db1=pd.read_csv("file_Demo_2007.csv")
db2=pd.read_csv("file_DEMO2009.csv")
db3=pd.read_csv("file_DEMO2011.csv")
db4=pd.read_csv("file_DEMO2013.csv")
db5=pd.read_csv("file_DEMO2015.csv")
db6=pd.read_csv("file_DEMO2017.csv")

In [6]:
df = pd.concat([df1, df2, df3, df4, df5, df6], ignore_index = True)
df
# So the total diffrent unique entries for 2007-2018 are 57414.

,SEQN,BMDSTATS,BMXWT,BMIWT,BMXRECUM,BMIRECUM,BMXHEAD,BMIHEAD,BMXHT,BMIHT,...,BMISUB,BMDBMIC,BMXSAD1,BMXSAD2,BMXSAD3,BMXSAD4,BMDAVSAD,BMDSADCM,BMXHIP,BMIHIP
0,41475.0,3.0,138.9,NaN,NaN,NaN,NaN,NaN,154.7,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,41476.0,1.0,22.0,NaN,NaN,NaN,NaN,NaN,120.4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,41477.0,1.0,83.9,NaN,NaN,NaN,NaN,NaN,167.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,41478.0,1.0,11.5,NaN,77.4,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,41479.0,1.0,65.7,NaN,NaN,NaN,NaN,NaN,154.4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57409,102952.0,1.0,49.0,NaN,NaN,NaN,NaN,NaN,156.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.3,NaN
57410,102953.0,1.0,97.4,NaN,NaN,NaN,NaN,NaN,164.9,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,112.8,NaN
57411,102954.0,1.0,69.1,NaN,NaN,NaN,NaN,NaN,162.6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.7,NaN
57412,102955.0,1.0,111.9,NaN,NaN,NaN,NaN,NaN,156.6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,128.3,NaN
57413,102956.0,1.0,111.5,NaN,NaN,NaN,NaN,NaN,175.8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.0,NaN

In [7]:
# We have derived the important parameters from above dataset depending upon our need for the project, i.e. Calulated BMI here.
a=df["SEQN"].values.tolist()
b=df["BMXBMI"].values.tolist()
data = {'SEQN': a,'BMXBMI': b}
df_BMI= pd.DataFrame(data)
df_BMI

           SEQN  BMXBMI
0       41475.0   58.04
1       41476.0   15.18
2       41477.0   30.05
3       41478.0     NaN
4       41479.0   27.56
...         ...     ...
57409  102952.0   20.00
57410  102953.0   35.80
57411  102954.0   26.10
57412  102955.0   45.60
57413  102956.0   36.10

[57414 rows x 2 columns]

In [8]:
df.isnull().sum()
# For cleaning our data, we have found the number of entries having no BMI_calculated.

SEQN            0
BMDSTATS        0
BMXWT         630
BMIWT       55073
BMXRECUM    50903
BMIRECUM    57262
BMXHEAD     56042
BMIHEAD     57414
BMXHT        4654
BMIHT       56109
BMXBMI       4723
BMXLEG      14185
BMILEG      55291
BMXARML      3150
BMIARML     55205
BMXARMC      3158
BMIARMC     55180
BMXWAIST     7124
BMIWAIST    54745
BMXTRI      39112
BMITRI      56013
BMXSUB      40425
BMISUB      54701
BMDBMIC     47196
BMXSAD1     36418
BMXSAD2     36418
BMXSAD3     56305
BMXSAD4     56305
BMDAVSAD    36418
BMDSADCM    55999
BMXHIP      51375
BMIHIP      57144
dtype: int64

In [9]:
db = pd.concat([db1, db2, db3, db4, db5, db6], ignore_index = True)
# so the there are additional entries avaliable in demographic dataset,which we can ignore at this moment.
db.isnull().sum()

SEQN            0
SDDSRVYR        0
RIDSTATR        0
RIDEXMON     2428
RIAGENDR        0
RIDAGEYR        0
RIDAGEMN    37429
RIDAGEEX    40620
RIDRETH1        0
DMQMILIT    46748
DMDBORN2    39156
DMDCITZN       27
DMDYRSUS    47985
DMDEDUC3    44392
DMDEDUC2    25072
DMDSCHOL    55219
DMDMARTL    25072
DMDHHSIZ        0
DMDFMSIZ        0
INDHHIN2     1214
INDFMIN2     1143
INDFMPIR     5798
RIDEXPRG    52314
DMDHRGND        0
DMDHRAGE     9254
DMDHRBR2    39701
DMDHREDU    10849
DMDHRMAR    10041
DMDHSEDU    33515
SIALANG         1
SIAPROXY       12
SIAINTRP        1
FIALANG      1225
FIAPROXY     1225
FIAINTRP     1225
MIALANG     17652
MIAPROXY    17650
MIAINTRP    17650
AIALANG     46620
WTINT2YR        0
WTMEC2YR        0
SDMVPSU         0
SDMVSTRA        0
RIDRETH3    20686
RIDEXAGY    56424
RIDEXAGM    44127
DMQMILIZ    35421
DMQADFC     57660
DMDBORN4    20686
AIALANGA    36832
DMDHHSZA    20686
DMDHHSZB    20686
DMDHHSZE    20686
DMDHRBR4    30998
DMDHRAGZ    50588
DMDHREDZ    51078
DMDHRMAZ    50779
DMDHSEDZ    55091
dtype: int64

In [10]:
db.to_csv('demographic.csv')
df.to_csv('BMI.csv')

In [11]:
dn1=pd.read_csv("Pregnancy2007.csv")
dn2=pd.read_csv("Pregnancy2009.csv")
dn3=pd.read_csv("Pregnancy2011.csv")
dn4=pd.read_csv("Pregnancy2013.csv")
dn5=pd.read_csv("Pregnancy2015.csv")
dn6=pd.read_csv("Pregnancy2017.csv")
dn = pd.concat([dn1, dn2, dn3, dn4, dn5, dn6], ignore_index = True)

In [12]:
dn.to_csv('pregnancy.csv')
# The total time it took to excute (in a 8GB RAM pc) is 10 second for the above operations.

# Cleaning the Data

In [13]:
db=pd.read_csv("filldata.csv")
db

,SEQN,WTDRD1,WTDR2D,DR1ILINE,DR1DRSTZ,DR1EXMER,DRABF,DRDINT,DR1DBIH,DR1DAY,...,DR1IM181,DR1IM201,DR1IM221,DR1IP182,DR1IP183,DR1IP184,DR1IP204,DR1IP205,DR1IP225,DR1IP226
0,4.147500e+04,5.394225e+04,5.881555e+04,1.000000e+00,1.000000e+00,2.300000e+01,2.000000e+00,2.000000e+00,0,5,...,0.034,0.000,0.0,0.011,0.000,0.0,0.0,0.0,0.0,0.0
1,4.147500e+04,5.394225e+04,5.881555e+04,2.000000e+00,1.000000e+00,2.300000e+01,2.000000e+00,2.000000e+00,0,5,...,0.000,0.000,0.0,0.014,0.000,0.0,0.0,0.0,0.0,0.0
2,4.147500e+04,5.394225e+04,5.881555e+04,3.000000e+00,1.000000e+00,2.300000e+01,2.000000e+00,2.000000e+00,0,5,...,0.000,0.000,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0
3,4.147500e+04,5.394225e+04,5.881555e+04,4.000000e+00,1.000000e+00,2.300000e+01,2.000000e+00,2.000000e+00,0,5,...,0.292,0.000,0.0,0.026,0.017,0.0,0.0,0.0,0.0,0.0
4,4.147500e+04,5.394225e+04,5.881555e+04,5.000000e+00,1.000000e+00,2.300000e+01,2.000000e+00,2.000000e+00,0,5,...,2.466,0.011,0.0,0.969,0.038,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
788995,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,10,5,...,0.000,0.000,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0
788996,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,10,5,...,0.000,0.000,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0
788997,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,10,5,...,0.000,0.000,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0
788998,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,10,5,...,0.000,0.000,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0
788999,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,10,5,...,0.000,0.000,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0

In [14]:
db1=db
# It is always advised to store your original dataset
db1

,SEQN,WTDRD1,WTDR2D,DR1ILINE,DR1DRSTZ,DR1EXMER,DRABF,DRDINT,DR1DBIH,DR1DAY,...,DR1IM181,DR1IM201,DR1IM221,DR1IP182,DR1IP183,DR1IP184,DR1IP204,DR1IP205,DR1IP225,DR1IP226
0,4.147500e+04,5.394225e+04,5.881555e+04,1.000000e+00,1.000000e+00,2.300000e+01,2.000000e+00,2.000000e+00,0,5,...,0.034,0.000,0.0,0.011,0.000,0.0,0.0,0.0,0.0,0.0
1,4.147500e+04,5.394225e+04,5.881555e+04,2.000000e+00,1.000000e+00,2.300000e+01,2.000000e+00,2.000000e+00,0,5,...,0.000,0.000,0.0,0.014,0.000,0.0,0.0,0.0,0.0,0.0
2,4.147500e+04,5.394225e+04,5.881555e+04,3.000000e+00,1.000000e+00,2.300000e+01,2.000000e+00,2.000000e+00,0,5,...,0.000,0.000,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0
3,4.147500e+04,5.394225e+04,5.881555e+04,4.000000e+00,1.000000e+00,2.300000e+01,2.000000e+00,2.000000e+00,0,5,...,0.292,0.000,0.0,0.026,0.017,0.0,0.0,0.0,0.0,0.0
4,4.147500e+04,5.394225e+04,5.881555e+04,5.000000e+00,1.000000e+00,2.300000e+01,2.000000e+00,2.000000e+00,0,5,...,2.466,0.011,0.0,0.969,0.038,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
788995,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,10,5,...,0.000,0.000,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0
788996,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,10,5,...,0.000,0.000,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0
788997,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,10,5,...,0.000,0.000,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0
788998,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,10,5,...,0.000,0.000,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0
788999,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,3.687825e-40,10,5,...,0.000,0.000,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0

In [15]:
df=pd.read_csv('clean_BMI.csv')
check_demo=pd.read_csv('demographic.csv')

In [16]:
Demo=check_demo[['SEQN','RIAGENDR','RIDAGEYR','RIDRETH1','INDFMPIR']].copy()
Demo.to_csv('Demographic.csv')

In [17]:
dn=pd.read_csv('pregnancy.csv') #pregnancy csv file(7283 rows Ã— 3 columns) 
dn.dropna()
dn=dn.drop(["Unnamed: 0"],axis=1)

df2=pd.read_csv('Demographic.csv')#The required Demographic dataset(59842 rows Ã— 5 columns).
df2=df2.drop(['Unnamed: 0'],axis=1)

df=df.drop(['Unnamed: 0'],axis=1)#df containing the BMI_Index of the entries.

In [18]:
l=[2.0]
dn=dn[dn.URXPREG.isin(l) == False]
# So now we are cleaning the data further with avaliable,
# 1 represents positive and 3 means Not done.

In [19]:
merge = pd.merge(df, dn, on="SEQN",how="left")
# We merge the pregnancy and BMI dataset.
merge1 = pd.merge(df2,merge,on='SEQN',how='left')#df2-demographic data
merge2 = pd.merge(merge1,db,on='SEQN',how='left')#db is the whole dataset.
# The dataset -(796264 rows Ã— 91 columns)

In [20]:
a=merge2.index[merge2['URXPREG'] == 1.0].tolist()
merge2=merge2.drop(merge2.index[a])
merge2=merge2.drop(['URXPREG'],axis=1)

In [21]:
merge2.to_csv('forKMeans.csv')

In [22]:
# Now we are cleaning the data further based on our objective,
merge2=merge2.drop(['WTDRD1', 'WTDR2D', 'DR1ILINE', 'DR1DRSTZ', 'DR1EXMER', 'DRABF',
       'DRDINT', 'DR1DBIH', 'DR1DAY', 'DR1LANG', 'DR1CCMNM', 'DR1CCMTX',
       'DR1FS', 'DR1_040Z', 'DR1MC',
       'DR1IGRMS', 'DR1IFIBE',
       'DR1IATOA', 'DR1IVARA', 'DR1IACAR', 'DR1IBCAR', 'DR1ICRYP',
       'DR1ILYCO', 'DR1ILZ', 
       'DR1IFOLA', 'DR1IFA', 'DR1IFF', 'DR1IFDFE', 'DR1ICHL',
       'DR1IB12A', 'DR1ICAFF', 'DR1ITHEO', 'DR1IALCO', 'DR1IMOIS', 'DR1IS040',
       'DR1IS060', 'DR1IS080', 'DR1IS100', 'DR1IS120', 'DR1IS140', 'DR1IS160',
       'DR1IS180', 'DR1IM161', 'DR1IM181', 'DR1IM201', 'DR1IM221', 'DR1IP182',
       'DR1IP183', 'DR1IP184', 'DR1IP204', 'DR1IP205', 'DR1IP225', 'DR1IP226'],axis=1)

In [23]:
merge2=merge2.dropna()

In [24]:
#Restricting the age between 20 to 65 years of the dataset
merge2=merge2.loc[(merge2["RIDAGEYR"] <= 65) & (merge2["RIDAGEYR"] >= 20)]

In [25]:
# This dataset is of restricted age,non-pregnancy and no-null value.
merge2.to_csv('fullyclean.csv')
merge2

,SEQN,RIAGENDR,RIDAGEYR,RIDRETH1,INDFMPIR,BMXBMI,DR1_020,DR1_030Z,DR1IFDCD,DR1IKCAL,...,DR1IVK,DR1ICALC,DR1IPHOS,DR1IMAGN,DR1IIRON,DR1IZINC,DR1ICOPP,DR1ISODI,DR1IPOTA,DR1ISELE
0,41475.0,2.0,62.0,5.0,1.83,58.04,6:00,1.0,64132010.0,114.0,...,5.4,19.0,40.0,22.0,1.89,0.34,0.109,6.0,442.0,1.0
1,41475.0,2.0,62.0,5.0,1.83,58.04,6:00,1.0,92101500.0,4.0,...,0.7,14.0,14.0,28.0,0.21,0.14,0.036,14.0,366.0,0.4
2,41475.0,2.0,62.0,5.0,1.83,58.04,6:00,1.0,91200040.0,14.0,...,0.0,0.0,0.0,0.0,0.00,0.00,0.000,17.0,0.0,0.0
3,41475.0,2.0,62.0,5.0,1.83,58.04,6:00,1.0,12120100.0,13.0,...,0.1,11.0,10.0,1.0,0.01,0.05,0.001,4.0,13.0,0.2
4,41475.0,2.0,62.0,5.0,1.83,58.04,8:00,1.0,52215200.0,198.0,...,2.2,82.0,79.0,14.0,2.13,0.34,0.090,405.0,99.0,14.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796259,102956.0,1.0,38.0,3.0,1.56,36.10,12:00,7.0,94100100.0,0.0,...,0.0,51.0,0.0,10.0,0.00,0.00,0.035,10.0,0.0,0.0
796260,102956.0,1.0,38.0,3.0,1.56,36.10,14:00,7.0,94100100.0,0.0,...,0.0,51.0,0.0,10.0,0.00,0.00,0.035,10.0,0.0,0.0
796261,102956.0,1.0,38.0,3.0,1.56,36.10,19:00,3.0,24124201.0,474.0,...,6.4,18.0,606.0,75.0,1.19,2.42,0.124,953.0,950.0,81.0
796262,102956.0,1.0,38.0,3.0,1.56,36.10,19:00,3.0,71508005.0,550.0,...,10.0,69.0,300.0,118.0,4.55,1.54,0.498,928.0,2257.0,1.9
796263,102956.0,1.0,38.0,3.0,1.56,36.10,19:00,3.0,92410550.0,257.0,...,0.0,10.0,0.0,5.0,0.58,0.21,0.005,94.0,10.0,0.0

In [26]:
merge2.describe()

,SEQN,RIAGENDR,RIDAGEYR,RIDRETH1,INDFMPIR,BMXBMI,DR1_030Z,DR1IFDCD,DR1IKCAL,DR1IPROT,...,DR1IVK,DR1ICALC,DR1IPHOS,DR1IMAGN,DR1IIRON,DR1IZINC,DR1ICOPP,DR1ISODI,DR1IPOTA,DR1ISELE
count,334891.000000,334891.000000,334891.000000,334891.000000,334891.000000,334891.000000,334891.000000,3.348910e+05,334891.000000,334891.000000,...,334891.000000,334891.000000,334891.000000,334891.000000,334891.000000,334891.000000,334891.000000,334891.000000,334891.000000,334891.000000
mean,71335.693897,1.515311,43.522764,3.038048,2.664464,29.240100,4.476280,6.260320e+07,140.767163,5.392932,...,7.185872,60.710007,89.068801,19.317900,0.938716,0.733156,0.081320,231.570732,168.859844,7.528496
std,17919.897161,0.499766,13.157477,1.211256,1.684227,7.158011,3.641398,2.765493e+07,199.427430,10.992461,...,43.646120,128.291212,151.389911,29.425878,2.075320,2.018106,0.212498,424.148323,255.230750,16.969480
min,41475.000000,1.000000,20.000000,1.000000,0.000000,13.600000,1.000000,1.110000e+07,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,55670.000000,1.000000,32.000000,2.000000,1.140000,24.170000,2.000000,4.220200e+07,10.000000,0.090000,...,0.000000,5.000000,4.000000,3.000000,0.040000,0.040000,0.011000,10.000000,13.000000,0.000000
50%,70291.000000,2.000000,44.000000,3.000000,2.340000,28.000000,3.000000,6.410010e+07,81.000000,1.130000,...,0.500000,16.000000,31.000000,10.000000,0.230000,0.180000,0.037000,63.000000,78.000000,0.600000
75%,86829.000000,2.000000,55.000000,4.000000,4.550000,32.800000,6.000000,9.210100e+07,187.000000,5.590000,...,3.900000,55.000000,111.000000,25.000000,0.990000,0.730000,0.095000,275.000000,222.000000,7.600000
max,102956.000000,2.000000,65.000000,5.000000,5.000000,82.900000,19.000000,9.534200e+07,4991.000000,356.900000,...,10150.300000,5429.000000,5444.000000,1447.000000,107.590000,444.950000,36.017000,13642.000000,15552.000000,897.800000